import { createHash } from 'node:crypto';
import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';

/**
 * Preload the Archivo (latin, variable width) font so the hero headline never
 * swaps faces mid-animation. Vite hashes the file name at build time, so the
 * tag is injected after bundling rather than written into index.html.
 */
function preloadUiFont(): Plugin {
  return {
    name: 'vibemotion:preload-ui-font',
    apply: 'build',
    transformIndexHtml: {
      order: 'post',
      handler(_html, ctx) {
        const asset = Object.keys(ctx.bundle ?? {}).find((f) =>
          /archivo-latin-wdth-normal.*\.woff2$/.test(f),
        );
        if (!asset) return [];
        return [
          {
            tag: 'link',
            attrs: {
              rel: 'preload',
              as: 'font',
              type: 'font/woff2',
              crossorigin: '',
              href: `${ctx.server ? '/' : '/VibeMotion/'}${asset}`,
            },
            injectTo: 'head-prepend',
          },
        ];
      },
    },
  };
}

/**
 * transformers.js points ONNX Runtime at jsDelivr for its WebAssembly (5.5 MB
 * brotli, cached immutably), but Vite still copies the 27 MB fallback file
 * that onnxruntime-web references. It is never fetched; keep it out of dist.
 */
function dropUnusedOrtWasm(): Plugin {
  return {
    name: 'vibemotion:drop-unused-ort-wasm',
    apply: 'build',
    generateBundle(_opts, bundle) {
      for (const key of Object.keys(bundle)) {
        if (/ort-wasm[^/]*\.wasm$/.test(key)) delete bundle[key];
      }
    },
  };
}

/**
 * A small service worker, generated at build time so it knows the hashed
 * file names: the app shell works offline once visited. Pages are
 * network-first (a new deploy always wins), hashed assets cache-first.
 * Range requests (video seeking) and other origins (model downloads, which
 * transformers.js and the HTTP cache already keep) pass straight through.
 */
function serviceWorker(): Plugin {
  return {
    name: 'vibemotion:service-worker',
    apply: 'build',
    generateBundle(_opts, bundle) {
      const base = '/VibeMotion/';
      // Precache only the landing shell (entry chunk, its CSS, the UI font).
      // The editor's chunks are cached the first time they're used, so a
      // landing-only visit doesn't download the editor in the background.
      const files = Object.values(bundle)
        .filter(
          (f) =>
            (f.type === 'chunk' && f.isEntry) ||
            (f.type === 'asset' && /^assets\/index-.*\.css$/.test(f.fileName)) ||
            /archivo-latin-wdth-normal/.test(f.fileName),
        )
        .map((f) => base + f.fileName);
      const shell = [base, `${base}favicon.svg`, `${base}manifest.webmanifest`, `${base}icon-192.png`, `${base}sample/poster.jpg`];
      const version = createHash('sha256').update(files.join('|')).digest('hex').slice(0, 12);
      const source = `// Generated by vite.config.ts. Cache version ${version}.
const CACHE = 'vm-${version}';
const PRECACHE = ${JSON.stringify([...shell, ...files])};
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('vm-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});
self.addEventListener('fetch', (e) => {
  const req = e.request;
  const url = new URL(req.url);
  if (req.method !== 'GET' || url.origin !== location.origin || !url.pathname.startsWith('${base}') || req.headers.has('range')) return;
  if (req.mode === 'navigate') {
    e.respondWith(
      fetch(req)
        .then((res) => {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put('${base}', copy));
          return res;
        })
        .catch(() => caches.match('${base}')),
    );
    return;
  }
  e.respondWith(
    caches.match(req).then(
      (hit) =>
        hit ||
        fetch(req).then((res) => {
          if (res.ok && url.pathname.startsWith('${base}assets/')) {
            const copy = res.clone();
            caches.open(CACHE).then((c) => c.put(req, copy));
          }
          return res;
        }),
    ),
  );
});
`;
      this.emitFile({ type: 'asset', fileName: 'sw.js', source });
    },
  };
}

export default defineConfig({
  base: '/VibeMotion/',
  plugins: [react(), preloadUiFont(), dropUnusedOrtWasm(), serviceWorker()],
  worker: { format: 'es', plugins: () => [dropUnusedOrtWasm()] },
  build: {
    target: 'es2022',
    sourcemap: false,
    assetsInlineLimit: 0,
    chunkSizeWarningLimit: 4096,
  },
  server: { port: 5311, strictPort: true },
  preview: { port: 5312, strictPort: true },
});
